# action.yml
name: 'Check if merged'
description: 'Check if branch is merged to another one'
author: Marco Carvalho
branding:
  icon: git-merge
  color: purple
inputs:
  destination_branch:  # id of input
    description: 'destination branch'
    required: true
    default: 'origin/staging'
  source_ref:
    description:  'source branch to check or GITHUB_REF will be used'
    required: true
    default: ${{ github.ref }} # format: refs/heads/branch/name
  test_run:
    description: 'do not use exit code if test run'
    required: false
    default: 'false'
outputs:
  is_merged: # id of output
    description: '0 - merged | 100 not merged'
runs:
  using: 'docker'
  image: 'Dockerfile'
