# action.yml
name: 'Check if merged'
description: 'Check if branch is merged to another one'
author: Marco Carvalho
branding:
  icon: git-merge
  color: purple
inputs:
  destination_branch:
    description: 'destination branch'
    required: true
    default: 'staging'
  github_token:
    description: default token to use
    required: true
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
