# action.yml
name: 'Check if merged'
description: 'Check if branch is merged to another one'
author: Marco Carvalho
branding:
  icon: git-merge
  color: purple
inputs:
  destination_branch:  # id of input
    description: 'destination branch'
    required: true
    default: 'staging'
  source_branch:
    description:  'source branch to check or GITHUB_REF will be used'
    required: false
outputs:
  is_merged: # id of output
    description: '0 - merged | 100 not merged'
runs:
  using: 'node16'
  main: 'dist/index.js'
