version: 1

update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    default_reviewers:
      - marcocarvalho
    default_assignees:
      - marcocarvalho
    default_labels:
      - "dependencies"
      - "dependabot"
